# –î–∞–Ω–Ω—ã–µ

–í –¥–∞–Ω–Ω—ã—Ö –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–∞ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ —Å —Ä–∞–∑–ª–∏—á–Ω—ã–º–∏ –º–µ—Ç—Ä–∏–∫–∞–º–∏ —Å–æ—Ü–∏–∞–ª—å–Ω—ã—Ö —Å–µ—Ç–µ–π (—Ä–µ–ø–æ—Å—Ç—ã, –ª–∞–π–∫–∏, –ø—Ä–æ—Å–º–æ—Ç—Ä—ã –∏ —Ç.–¥.). –ò—Å–ø–æ–ª—å–∑—É—é—Ç—Å—è –¥–∞–Ω–Ω—ã–µ –∑–∞ –æ–¥–∏–Ω –º–µ—Å—è—Ü (–¥–µ–∫–∞–±—Ä—å 2022 –≥–æ–¥–∞).

–ü–æ–ª–Ω—ã–π –¥–∞—Ç–∞—Å–µ—Ç –º–æ–∂–Ω–æ –Ω–∞–π—Ç–∏ –ø–æ —Å—Å—ã–ª–∫–µ: https://www.kaggle.com/datasets/ramjasmaurya/top-1000-social-media-channels.

# –ö–∞–∫–∏–µ –¥–∞–Ω–Ω—ã–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω—ã?

–ò—Å–ø–æ–ª—å–∑—É—é—Ç—Å—è –¥–∞—Ç–∞—Å–µ—Ç—ã —Å–æ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–æ–π –ø–æ —Ç—Ä–µ–º —Å–æ—Ü–∏–∞–ª—å–Ω—ã–º —Å–µ—Ç—è–º - Instagram, TikTok, YouTube.

### Instagram

- Rank - –∫–æ–ª–æ–Ω–∫–∞ —Å –∏–Ω–¥–µ–∫—Å–æ–º
- name - –∏–º—è –±–ª–æ–≥–µ—Ä–∞
- instagram name - –Ω–∏–∫ –±–ª–æ–≥–µ—Ä–∞ –≤ Instagram
- Category_1 - –∫–∞—Ç–µ–≥–æ—Ä–∏—è –ø—Ä–æ–∏–∑–≤–æ–¥–∏–º–æ–≥–æ –±–ª–æ–≥–µ—Ä–æ–º –∫–æ–Ω—Ç–µ–Ω—Ç–∞ 1
- Category_2 - –∫–∞—Ç–µ–≥–æ—Ä–∏—è –ø—Ä–æ–∏–∑–≤–æ–¥–∏–º–æ–≥–æ –±–ª–æ–≥–µ—Ä–æ–º –∫–æ–Ω—Ç–µ–Ω—Ç–∞ 2
- followers - –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤
- country - –≤ –∫–∞–∫–æ–π —Å—Ç—Ä–∞–Ω–µ –ø—Ä–æ–∂–∏–≤–∞–µ—Ç –æ—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è –±–ª–æ–≥–µ—Ä–∞
- Eng. (Auth.) - –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤ (–≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏—è –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤ —Å –∫–æ–Ω—Ç–µ–Ω—Ç–æ–º –±–ª–æ–≥–µ—Ä–∞)
- Eng. (Avg.) - –æ–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å (–≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏—è –∫–∞–∫ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤ —Ç–∞–∫ –∏ –Ω–µ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤)

### TikTok

- Rank - –∫–æ–ª–æ–Ω–∫–∞ —Å –∏–Ω–¥–µ–∫—Å–æ–º
- Tiktoker name - –Ω–∏–∫ –±–ª–æ–≥–µ—Ä–∞ –≤ TikTok
- Tiktok name - –∏–º—è –±–ª–æ–≥–µ—Ä–∞
- followers - –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤
- views(avg) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –ø—Ä–æ—Å–º–æ—Ç—Ä–æ–≤
- likes(avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –ª–∞–π–∫–æ–≤
- comments(avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤
- shares(avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ —Ä–µ–ø–æ—Å—Ç–æ–≤

### YouTube

- s.no - –∫–æ–ª–æ–Ω–∫–∞ —Å –∏–Ω–¥–µ–∫—Å–æ–º
- Youtube channel - –Ω–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞
- youtuber name - –∏–º—è –±–ª–æ–≥–µ—Ä–∞
- Category - –∫–∞—Ç–µ–≥–æ—Ä–∏—è –ø—Ä–æ–∏–∑–≤–æ–¥–∏–º–æ–≥–æ –±–ª–æ–≥–µ—Ä–æ–º –∫–æ–Ω—Ç–µ–Ω—Ç–∞ 1
- Category-2 - –∫–∞—Ç–µ–≥–æ—Ä–∏—è –ø—Ä–æ–∏–∑–≤–æ–¥–∏–º–æ–≥–æ –±–ª–æ–≥–µ—Ä–æ–º –∫–æ–Ω—Ç–µ–Ω—Ç–∞ 2
- Followers - –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤
- Country - –≤ –∫–∞–∫–æ–π —Å—Ç—Ä–∞–Ω–µ –ø—Ä–æ–∂–∏–≤–∞–µ—Ç –æ—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è –±–ª–æ–≥–µ—Ä–∞
- Views (Avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –ø—Ä–æ—Å–º–æ—Ç—Ä–æ–≤
- Likes (Avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –ª–∞–π–∫–æ–≤
- Comments (Avg.) - —Å—Ä–µ–¥–Ω–µ–µ —á–∏—Å–ª–æ –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤

# –ó–∞–¥–∞—á–∞

–ü—Ä–µ–¥–æ–±—Ä–∞–±–æ—Ç–∞—Ç—å –¥–∞–Ω–Ω—ã–µ –¥–ª—è —Å–æ—Å—Ç–∞–≤–ª–µ–Ω–∏—è –¥–∞—à–±–æ—Ä–¥–∞ –≤ Microsoft Power BI. –î–∞—à–±–æ—Ä–¥ –¥–æ–ª–∂–µ–Ω —É–ø—Ä–æ—â–∞—Ç—å –ø–æ–∏—Å–∫ –±–ª–æ–≥–µ—Ä–æ–≤, —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤—É—é—â–∏—Ö –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã–º —É—Å–ª–æ–≤–∏—è–º.

### Instagram

–°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –ø–æ:

- —Ä–∞–Ω–≥—É (—á–∏—Å–ª—É –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤)
- –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –∫–æ–Ω—Ç–µ–Ω—Ç–∞
- —Å—Ç—Ä–∞–Ω–µ, –≤ –∫–æ—Ç–æ—Ä–æ–π –ø—Ä–æ–∂–∏–≤–∞–µ—Ç –æ—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è

### TikTok

–°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –ø–æ:

- —Ä–∞–Ω–≥—É (—á–∏—Å–ª—É –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤)
- —É—Ä–æ–≤–Ω—é –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤
- —É—Ä–æ–≤–Ω—é –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∫–æ–Ω—Ç–µ–Ω—Ç–∞ –±–ª–æ–≥–µ—Ä–∞

### YouTube

–°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –ø–æ:

- —Ä–∞–Ω–≥—É (—á–∏—Å–ª—É –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤)
- –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ –∫–æ–Ω—Ç–µ–Ω—Ç–∞
- —Å—Ç—Ä–∞–Ω–µ, –≤ –∫–æ—Ç–æ—Ä–æ–π –ø—Ä–æ–∂–∏–≤–∞–µ—Ç –æ—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è

In [1]:
# –ó–∞–≥—Ä—É–∑–∫–∞ –Ω—É–∂–Ω—ã—Ö –±–∏–±–ª–∏–æ—Ç–µ–∫
import re

import pandas as pd
import numpy as np

# 1. Instagram

In [2]:
# –ó–∞–≥—Ä—É–∑–∫–∞ –¥–∞–Ω–Ω—ã—Ö
df_inst = pd.read_csv('data/instagram/social media influencers-INSTAGRAM - -DEC 2022.csv')
print(df_inst.shape)
df_inst.head()

(1000, 9)

,Rank,name,instagram name,Category_1,Category_2,followers,country,Eng. (Auth.),Eng. (Avg.)
0,1,leomessi,Leo Messi,Sports with a ball,Family,409.8M,Argentina,17.8M,23.4M
1,2,cristiano,Cristiano Ronaldo,Sports with a ball,NaN,523M,India,11.7M,14.7M
2,3,neymarjr,NJ üáßüá∑,Sports with a ball,NaN,198.9M,Brazil,6.7M,9.5M
3,4,kyliejenner,Kylie ü§ç,Fashion,Modeling,376.3M,United States,2.7M,4.3M
4,5,kendalljenner,Kendall,Modeling,Fashion,268M,United States,3.2M,5M

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –Ω—É–∂–Ω—ã–µ –∫–æ–ª–æ–Ω–∫–∏, –æ—Å—Ç–∞–ª—å–Ω—ã–µ —É–¥–∞–ª–∏–º.

In [3]:
df_inst = df_inst.drop(columns=['Rank', 'Category_2'])

df_inst = df_inst.rename(columns={'name': '–ù–∏–∫ Instagram',
                                  'instagram name': '–ò–º—è',
                                  'followers': '–ü–æ–¥–ø–∏—Å—á–∏–∫–∏',
                                  'country': '–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è',
                                  'Eng. (Auth.)': '–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤',
                                  'Eng. (Avg.)': '–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å',
                                  'Category_1': '–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞'})

df_inst = df_inst[['–ù–∏–∫ Instagram', '–ò–º—è', '–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è', '–ü–æ–¥–ø–∏—Å—á–∏–∫–∏', '–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤', '–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å', '–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞']]

df_inst

,–ù–∏–∫ Instagram,–ò–º—è,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤,–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞
0,leomessi,Leo Messi,Argentina,409.8M,17.8M,23.4M,Sports with a ball
1,cristiano,Cristiano Ronaldo,India,523M,11.7M,14.7M,Sports with a ball
2,neymarjr,NJ üáßüá∑,Brazil,198.9M,6.7M,9.5M,Sports with a ball
3,kyliejenner,Kylie ü§ç,United States,376.3M,2.7M,4.3M,Fashion
4,kendalljenner,Kendall,United States,268M,3.2M,5M,Modeling
...,...,...,...,...,...,...,...
995,thiago6,Thiago Alcantara,United Kingdom,10.4M,129.9K,222.7K,Sports with a ball
996,soycintiacossio,Cintia Cossio,Colombia,6M,313.4K,390.6K,Modeling
997,feat.dino,Ïù¥Ï∞¨,South Korea,2.7M,716.6K,876.4K,Lifestyle
998,djokernole,Novak Djokovic,United States,11.8M,158.6K,197.5K,Sports with a ball
999,ravindra.jadeja,Ravindrasinh jadeja,India,4.8M,388.9K,485.1K,Lifestyle

–ü–æ—Å–º–æ—Ç—Ä–∏–º, –µ—Å—Ç—å –ª–∏ –≤ –¥–∞–Ω–Ω—ã—Ö –ø—Ä–æ–ø—É—Å–∫–∏.

In [4]:
df_inst.isnull().sum()

–ù–∏–∫ Instagram                 0
–ò–º—è                          19
–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è            1
–ü–æ–¥–ø–∏—Å—á–∏–∫–∏                    0
–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤     0
–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å           0
–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞           50
dtype: int64

In [5]:
df_inst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   –ù–∏–∫ Instagram              1000 non-null   object
 1   –ò–º—è                        981 non-null    object
 2   –û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è         999 non-null    object
 3   –ü–æ–¥–ø–∏—Å—á–∏–∫–∏                 1000 non-null   object
 4   –í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤  1000 non-null   object
 5   –û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å        1000 non-null   object
 6   –ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞         950 non-null    object
dtypes: object(7)
memory usage: 54.8+ KB

–ß–∏—Å–ª–æ–≤—ã–µ –¥–∞–Ω–Ω—ã–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω—ã –≤ –≤–∏–¥–µ —Å—Ç—Ä–æ–∫, –ø–æ—ç—Ç–æ–º—É –ø—Ä–æ–≤–µ–¥–µ–º –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –∫ —á–∏—Å–ª–æ–≤–æ–º—É —Ç–∏–ø—É –¥–∞–Ω–Ω—ã—Ö.

In [6]:
def str_to_int(str_number):
    '''
    –§—É–Ω–∫—Ü–∏—è –¥–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è –∏–∑ —Å—Ç—Ä–æ–∫–∏ —á–∏—Å–ª–∞.
    –ï—Å–ª–∏ –≤ —Å—Ç—Ä–æ–∫–µ –µ—Å—Ç—å —Å–∏–º–≤–æ–ª 'M', —Å—Ç—Ä–æ–∫–∞ –ø—Ä–µ–æ–±—Ä–∞–∑—É–µ—Ç—Å—è –≤ —á–∏—Å–ª–æ –∏ —É–º–Ω–æ–∂–∞–µ—Ç—Å—è –Ω–∞ –º–∏–ª–ª–∏–æ–Ω.
    –ï—Å–ª–∏ –≤ —Å—Ç—Ä–æ–∫–µ –µ—Å—Ç—å —Å–∏–º–≤–æ–ª 'K', —Å—Ç—Ä–æ–∫–∞ –ø—Ä–µ–æ–±—Ä–∞–∑—É–µ—Ç—Å—è –≤ —á–∏—Å–ª–æ –∏ —É–º–Ω–æ–∂–∞–µ—Ç—Å—è –Ω–∞ —Ç—ã—Å—è—á—É.
    –ï—Å–ª–∏ –Ω–µ—Ç –Ω–∏ –æ–¥–Ω–æ–≥–æ –∏–∑ —ç—Ç–∏—Ö —Å–∏–º–≤–æ–ª–æ–≤, —Ç–æ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç—Å—è –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–Ω–∞—è —Å—Ç—Ä–æ–∫–∞.
    '''
    if 'M' in str_number:
        str_number = str_number.replace('M', '')
        str_number = float(str_number) * 1000000

        return str_number
    
    elif 'K' in str_number:
        str_number = str_number.replace('K', '')
        str_number = float(str_number) * 1000

        return str_number

    else:
        str_number = float(str_number)

        return str_number

In [7]:
df_inst['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'] = df_inst['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'].apply(str_to_int)

df_inst['–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤'] = df_inst['–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤'].apply(str_to_int)

df_inst['–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å'] = df_inst['–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å'].apply(str_to_int)

–°–¥–µ–ª–∞–µ–º –∫–æ–ª–æ–Ω–∫—É —Å —Ä–∞–Ω–≥–æ–º –±–ª–æ–≥–µ—Ä–æ–≤ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤.

In [8]:
def inst_ranking(sub_count):
    '''
    –§—É–Ω–∫—Ü–∏—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Ä–∞–Ω–≥ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –ø–µ—Ä–µ–¥–∞–Ω–Ω–æ–≥–æ —á–∏—Å–ª–∞.
    –ë–æ–ª—å—à–µ 100 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–µ–≥–∞".
    –ë–æ–ª—å—à–µ 30 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 100 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∞–∫—Ä–æ".
    –ë–æ–ª—å—à–µ 10 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 30 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∏–∫—Ä–æ".
    –ú–µ–Ω—å—à–µ 10 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ù–∞–Ω–æ".
    '''
    if sub_count > 100000000:
        return '–ú–µ–≥–∞ (>100M)'
    elif (sub_count > 30000000) and (sub_count < 100000000):
        return '–ú–∞–∫—Ä–æ (>30M) & (<100M)'
    elif (sub_count > 10000000) and (sub_count < 30000000):
        return '–ú–∏–∫—Ä–æ (>10M) & (<30M)'
    else:
        return '–ù–∞–Ω–æ (<10M)'

In [9]:
df_inst['–†–∞–Ω–≥'] = df_inst['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'].apply(inst_ranking)

–£–¥–∞–ª–∏–º –¥—É–±–ª–∏–∫–∞—Ç—ã –∏ –ø—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.

In [10]:
df_inst = df_inst.drop_duplicates()
df_inst = df_inst.dropna()
df_inst

,–ù–∏–∫ Instagram,–ò–º—è,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤,–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,leomessi,Leo Messi,Argentina,409800000.0,17800000.0,23400000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
1,cristiano,Cristiano Ronaldo,India,523000000.0,11700000.0,14700000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
2,neymarjr,NJ üáßüá∑,Brazil,198900000.0,6700000.0,9500000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
3,kyliejenner,Kylie ü§ç,United States,376300000.0,2700000.0,4300000.0,Fashion,–ú–µ–≥–∞ (>100M)
4,kendalljenner,Kendall,United States,268000000.0,3200000.0,5000000.0,Modeling,–ú–µ–≥–∞ (>100M)
...,...,...,...,...,...,...,...,...
995,thiago6,Thiago Alcantara,United Kingdom,10400000.0,129900.0,222700.0,Sports with a ball,–ú–∏–∫—Ä–æ (>10M) & (<30M)
996,soycintiacossio,Cintia Cossio,Colombia,6000000.0,313400.0,390600.0,Modeling,–ù–∞–Ω–æ (<10M)
997,feat.dino,Ïù¥Ï∞¨,South Korea,2700000.0,716600.0,876400.0,Lifestyle,–ù–∞–Ω–æ (<10M)
998,djokernole,Novak Djokovic,United States,11800000.0,158600.0,197500.0,Sports with a ball,–ú–∏–∫—Ä–æ (>10M) & (<30M)
999,ravindra.jadeja,Ravindrasinh jadeja,India,4800000.0,388900.0,485100.0,Lifestyle,–ù–∞–Ω–æ (<10M)

–ö–∞–∫–æ–º –æ–±—Ä–∞–∑–æ–º —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–∏–ª–∏—Å—å —Ä–∞–Ω–≥–∏ –±–ª–æ–≥–µ—Ä–æ–≤?

In [11]:
df_inst['–†–∞–Ω–≥'].value_counts()

–†–∞–Ω–≥
–ú–∏–∫—Ä–æ (>10M) & (<30M)     478
–ù–∞–Ω–æ (<10M)               240
–ú–∞–∫—Ä–æ (>30M) & (<100M)    175
–ú–µ–≥–∞ (>100M)               30
Name: count, dtype: int64

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –∑–Ω–∞—á–µ–Ω–∏—è –∫–æ–ª–æ–Ω–∫–∏ —Å–æ —Å—Ç—Ä–∞–Ω–∞–º–∏ –∞—É–¥–∏—Ç–æ—Ä–∏–∏.

In [12]:
df_inst = df_inst.replace({'–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è': {'Argentina': '–ê—Ä–≥–µ–Ω—Ç–∏–Ω–∞',
                                                  'India': '–ò–Ω–¥–∏—è',
                                                  'Brazil': '–ë—Ä–∞–∑–∏–ª–∏—è',
                                                  'United States': '–°–®–ê',
                                                  'France': '–§—Ä–∞–Ω—Ü–∏—è',
                                                  'South Korea': '–Æ–∂–Ω–∞—è –ö–æ—Ä–µ—è',
                                                  'Indonesia': '–ò–Ω–¥–æ–Ω–µ–∑–∏—è',
                                                  'Mexico': '–ú–µ–∫—Å–∏–∫–∞',
                                                  'Ethiopia': '–≠—Ñ–∏–æ–ø–∏—è',
                                                  'Spain': '–ò—Å–ø–∞–Ω–∏—è',
                                                  'Turkey': '–¢—É—Ä—Ü–∏—è',
                                                  'Italy': '–ò—Ç–∞–ª–∏—è',
                                                  'Morocco': '–ú–æ—Ä–æ–∫–∫–æ',
                                                  'Poland': '–ü–æ–ª—å—à–∞',
                                                  'China': '–ö–∏—Ç–∞–π',
                                                  'United Kingdom': '–í–µ–ª–∏–∫–æ–±—Ä–∏—Ç–∞–Ω–∏—è',
                                                  'Iran': '–ò—Ä–∞–Ω',
                                                  'Russia': '–†–æ—Å—Å–∏—è',
                                                  'Colombia': '–ö–æ–ª—É–º–±–∏—è',
                                                  'Australia': '–ê–≤—Å—Ç—Ä–∞–ª–∏—è',
                                                  'Philippines': '–§–∏–ª–∏–ø–ø–∏–Ω—ã',
                                                  'Yemen': '–ô–µ–º–µ–Ω',
                                                  'Egypt': '–ï–≥–∏–ø–µ—Ç',
                                                  'United Arab Emirates': '–û–ê–≠',
                                                  'Germany': '–ì–µ—Ä–º–∞–Ω–∏—è',
                                                  'Thailand': '–¢–∞–∏–ª–∞–Ω–¥',
                                                  'Portugal': '–ü–æ—Ä—Ç—É–≥–∞–ª–∏—è',
                                                  'Nigeria': '–ù–∏–≥–µ—Ä–∏—è',
                                                  'Iraq': '–ò—Ä–∞–∫',
                                                  'Algeria': '–ê–ª–∂–∏—Ä',
                                                  'Albania': '–ê–ª–±–∞–Ω–∏—è',
                                                  'Syria': '–°–∏—Ä–∏—è',
                                                  'Japan': '–Ø–ø–æ–Ω–∏—è',
                                                  'Chile': '–ß–∏–ª–∏'}})

df_inst

,–ù–∏–∫ Instagram,–ò–º—è,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤,–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,leomessi,Leo Messi,–ê—Ä–≥–µ–Ω—Ç–∏–Ω–∞,409800000.0,17800000.0,23400000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
1,cristiano,Cristiano Ronaldo,–ò–Ω–¥–∏—è,523000000.0,11700000.0,14700000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
2,neymarjr,NJ üáßüá∑,–ë—Ä–∞–∑–∏–ª–∏—è,198900000.0,6700000.0,9500000.0,Sports with a ball,–ú–µ–≥–∞ (>100M)
3,kyliejenner,Kylie ü§ç,–°–®–ê,376300000.0,2700000.0,4300000.0,Fashion,–ú–µ–≥–∞ (>100M)
4,kendalljenner,Kendall,–°–®–ê,268000000.0,3200000.0,5000000.0,Modeling,–ú–µ–≥–∞ (>100M)
...,...,...,...,...,...,...,...,...
995,thiago6,Thiago Alcantara,–í–µ–ª–∏–∫–æ–±—Ä–∏—Ç–∞–Ω–∏—è,10400000.0,129900.0,222700.0,Sports with a ball,–ú–∏–∫—Ä–æ (>10M) & (<30M)
996,soycintiacossio,Cintia Cossio,–ö–æ–ª—É–º–±–∏—è,6000000.0,313400.0,390600.0,Modeling,–ù–∞–Ω–æ (<10M)
997,feat.dino,Ïù¥Ï∞¨,–Æ–∂–Ω–∞—è –ö–æ—Ä–µ—è,2700000.0,716600.0,876400.0,Lifestyle,–ù–∞–Ω–æ (<10M)
998,djokernole,Novak Djokovic,–°–®–ê,11800000.0,158600.0,197500.0,Sports with a ball,–ú–∏–∫—Ä–æ (>10M) & (<30M)
999,ravindra.jadeja,Ravindrasinh jadeja,–ò–Ω–¥–∏—è,4800000.0,388900.0,485100.0,Lifestyle,–ù–∞–Ω–æ (<10M)

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –∑–Ω–∞—á–µ–Ω–∏—è –∫–æ–ª–æ–Ω–∫–∏ —Å –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º–∏ –∫–æ–Ω—Ç–µ–Ω—Ç–∞.

In [13]:
df_inst = df_inst.replace({'–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞': {'Sports with a ball': '–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º',
                                                  'Fashion': '–ú–æ–¥–∞',
                                                  'Modeling': '–ú–æ–¥–µ–ª—å',
                                                  'Music': '–ú—É–∑—ã–∫–∞',
                                                  'Photography': '–§–æ—Ç–æ–≥—Ä–∞—Ñ–∏—è',
                                                  'Lifestyle': '–°—Ç–∏–ª—å –∂–∏–∑–Ω–∏',
                                                  'Fitness & Gym': '–§–∏—Ç–Ω–µ—Å',
                                                  'Art/Artists': '–ò—Å–∫—É—Å—Å—Ç–≤–æ/–•—É–¥–æ–∂–Ω–∏–∫–∏',
                                                  'Cinema & Actors/actresses': '–ö–∏–Ω–æ –∏ –ê–∫—Ç–µ—Ä—ã/–ê–∫—Ç—Ä–∏—Å—ã',
                                                  'Finance & Economics': '–§–∏–Ω–∞–Ω—Å—ã –∏ –≠–∫–æ–Ω–æ–º–∏–∫–∞',
                                                  'Science': '–ù–∞—É–∫–∞',
                                                  'Shows': '–®–æ—É',
                                                  'Beauty': '–ö—Ä–∞—Å–æ—Ç–∞',
                                                  'Humor & Fun & Happiness': '–Æ–º–æ—Ä/–®—É—Ç–∫–∏',
                                                  'Family': '–°–µ–º—å—è',
                                                  'Racing Sports': '–ì–æ–Ω–æ—á–Ω—ã–µ –≤–∏–¥—ã —Å–ø–æ—Ä—Ç–∞',
                                                  'Clothing & Outfits': '–û–¥–µ–∂–¥–∞',
                                                  'Computers & Gadgets': '–ö–æ–º–ø—å—é—Ç–µ—Ä—ã –∏ –ì–∞–¥–∂–µ—Ç—ã',
                                                  'Food & Cooking': '–ï–¥–∞',
                                                  'Nature & landscapes': '–ü—Ä–∏—Ä–æ–¥–∞',
                                                  'Literature & Journalism': '–õ–∏—Ç–µ—Ä–∞—Ç—É—Ä–∞ –∏ –ñ—É—Ä–Ω–∞–ª–∏—Å—Ç–∏–∫–∞',
                                                  'Business & Careers': '–ë–∏–∑–Ω–µ—Å –∏ –ö–∞—Ä—å–µ—Ä–∞',
                                                  'Cars & Motorbikes': '–ê–≤—Ç–æ–º–æ–±–∏–ª–∏ –∏ –ú–æ—Ç–æ—Ü–∏–∫–ª—ã',
                                                  'Luxury': '–ü—Ä–µ–¥–º–µ—Ç—ã —Ä–æ—Å–∫–æ—à–∏',
                                                  'Gaming': '–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã',
                                                  'Machinery & Technologies': '–ú–∞—à–∏–Ω—ã –∏ —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏–∏',
                                                  'Adult content': '–ö–æ–Ω—Ç–µ–Ω—Ç –¥–ª—è –≤–∑—Ä–æ—Å–ª—ã—Ö',
                                                  'Animals': '–ñ–∏–≤–æ—Ç–Ω—ã–µ',
                                                  'Education': '–û–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ',
                                                  'Water sports': '–í–æ–¥–Ω—ã–µ –≤–∏–¥—ã —Å–ø–æ—Ä—Ç–∞',
                                                  'Winter sports': '–ó–∏–º–Ω–∏–µ –≤–∏–¥—ã —Å–ø–æ—Ä—Ç–∞',
                                                  'Travel': '–ü—É—Ç–µ—à–µ—Å—Ç–≤–∏—è'}})

df_inst

,–ù–∏–∫ Instagram,–ò–º—è,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤,–û–±—â–∞—è –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,leomessi,Leo Messi,–ê—Ä–≥–µ–Ω—Ç–∏–Ω–∞,409800000.0,17800000.0,23400000.0,–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º,–ú–µ–≥–∞ (>100M)
1,cristiano,Cristiano Ronaldo,–ò–Ω–¥–∏—è,523000000.0,11700000.0,14700000.0,–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º,–ú–µ–≥–∞ (>100M)
2,neymarjr,NJ üáßüá∑,–ë—Ä–∞–∑–∏–ª–∏—è,198900000.0,6700000.0,9500000.0,–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º,–ú–µ–≥–∞ (>100M)
3,kyliejenner,Kylie ü§ç,–°–®–ê,376300000.0,2700000.0,4300000.0,–ú–æ–¥–∞,–ú–µ–≥–∞ (>100M)
4,kendalljenner,Kendall,–°–®–ê,268000000.0,3200000.0,5000000.0,–ú–æ–¥–µ–ª—å,–ú–µ–≥–∞ (>100M)
...,...,...,...,...,...,...,...,...
995,thiago6,Thiago Alcantara,–í–µ–ª–∏–∫–æ–±—Ä–∏—Ç–∞–Ω–∏—è,10400000.0,129900.0,222700.0,–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º,–ú–∏–∫—Ä–æ (>10M) & (<30M)
996,soycintiacossio,Cintia Cossio,–ö–æ–ª—É–º–±–∏—è,6000000.0,313400.0,390600.0,–ú–æ–¥–µ–ª—å,–ù–∞–Ω–æ (<10M)
997,feat.dino,Ïù¥Ï∞¨,–Æ–∂–Ω–∞—è –ö–æ—Ä–µ—è,2700000.0,716600.0,876400.0,–°—Ç–∏–ª—å –∂–∏–∑–Ω–∏,–ù–∞–Ω–æ (<10M)
998,djokernole,Novak Djokovic,–°–®–ê,11800000.0,158600.0,197500.0,–í–∏–¥—ã —Å–ø–æ—Ä—Ç–∞ —Å –º—è—á–æ–º,–ú–∏–∫—Ä–æ (>10M) & (<30M)
999,ravindra.jadeja,Ravindrasinh jadeja,–ò–Ω–¥–∏—è,4800000.0,388900.0,485100.0,–°—Ç–∏–ª—å –∂–∏–∑–Ω–∏,–ù–∞–Ω–æ (<10M)

In [14]:
# –°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ –¥–∞—Ç–∞—Å–µ—Ç–∞
# df_inst.to_excel('data/df_inst.xlsx', index=False)

# 2. TikTok

In [15]:
# –ó–∞–≥—Ä—É–∑–∫–∞ –¥–∞–Ω–Ω—ã—Ö
df_tiktok = pd.read_csv('data/tiktok/social media influencers-TIKTOK - ---DEC 2022.csv')
print(df_tiktok.shape)
df_tiktok.head()

(1000, 8)

,Rank,Tiktoker name,Tiktok name,followers,views(avg),likes(avg.),comments(avg.),shares(avg.)
0,1,mrbeast,MrBeast,60.3M,29.2M,3.5M,30.8K,7.2K
1,2,karolg,Karol G,42.4M,23.7M,3.4M,21.7K,25.7K
2,3,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8.9M,48.9M,998.4K,16.3K,60.9K
3,4,centralcee,CentralCee,4.4M,19.8M,3.6M,23.3K,24.2K
4,5,adinross,adin,6.1M,21.1M,3.3M,17.5K,25.3K

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –Ω—É–∂–Ω—ã–µ –∫–æ–ª–æ–Ω–∫–∏, –æ—Å—Ç–∞–ª—å–Ω—ã–µ —É–¥–∞–ª–∏–º.

In [16]:
df_tiktok = df_tiktok.drop(columns=['Rank'])

df_tiktok = df_tiktok.rename(columns={'Tiktoker name': '–ù–∏–∫ TikTok',
                                      'Tiktok name': '–ò–º—è',
                                      'followers': '–ü–æ–¥–ø–∏—Å—á–∏–∫–∏',
                                      'views(avg)': '–ü—Ä–æ—Å–º–æ—Ç—Ä—ã',
                                      'likes(avg.)': '–õ–∞–π–∫–∏',
                                      'comments(avg.)': '–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏',
                                      'shares(avg.)': '–†–µ–ø–æ—Å—Ç—ã'})

df_tiktok

,–ù–∏–∫ TikTok,–ò–º—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–†–µ–ø–æ—Å—Ç—ã
0,mrbeast,MrBeast,60.3M,29.2M,3.5M,30.8K,7.2K
1,karolg,Karol G,42.4M,23.7M,3.4M,21.7K,25.7K
2,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8.9M,48.9M,998.4K,16.3K,60.9K
3,centralcee,CentralCee,4.4M,19.8M,3.6M,23.3K,24.2K
4,adinross,adin,6.1M,21.1M,3.3M,17.5K,25.3K
...,...,...,...,...,...,...,...
995,jiembasands,Jiemba Sands,4.9M,3.4M,247.4K,207,264
996,crissa_ace,Crissa Jackson,14.9M,1.6M,141.7K,1.2K,580
997,ichadude,Alyssa & Dude,468.8K,2.3M,85.5K,997,1K
998,kanebrown,Kane Brown,5.2M,1.7M,96.7K,1.3K,1.2K
999,nnennab_,Nnenna B | NYC Creator & Actor,149.1K,606.2K,79.5K,2.1K,6.1K

–ü–æ—Å–º–æ—Ç—Ä–∏–º, –µ—Å—Ç—å –ª–∏ –≤ –¥–∞–Ω–Ω—ã—Ö –ø—Ä–æ–ø—É—Å–∫–∏.

In [17]:
df_tiktok.isnull().sum()

–ù–∏–∫ TikTok     0
–ò–º—è            0
–ü–æ–¥–ø–∏—Å—á–∏–∫–∏     0
–ü—Ä–æ—Å–º–æ—Ç—Ä—ã      0
–õ–∞–π–∫–∏          0
–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏    0
–†–µ–ø–æ—Å—Ç—ã        0
dtype: int64

In [18]:
df_tiktok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   –ù–∏–∫ TikTok   1000 non-null   object
 1   –ò–º—è          1000 non-null   object
 2   –ü–æ–¥–ø–∏—Å—á–∏–∫–∏   1000 non-null   object
 3   –ü—Ä–æ—Å–º–æ—Ç—Ä—ã    1000 non-null   object
 4   –õ–∞–π–∫–∏        1000 non-null   object
 5   –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏  1000 non-null   object
 6   –†–µ–ø–æ—Å—Ç—ã      1000 non-null   object
dtypes: object(7)
memory usage: 54.8+ KB

–ß–∏—Å–ª–æ–≤—ã–µ –¥–∞–Ω–Ω—ã–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω—ã –≤ –≤–∏–¥–µ —Å—Ç—Ä–æ–∫, –ø–æ—ç—Ç–æ–º—É –ø—Ä–æ–≤–µ–¥–µ–º –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –∫ —á–∏—Å–ª–æ–≤–æ–º—É —Ç–∏–ø—É –¥–∞–Ω–Ω—ã—Ö.

In [19]:
df_tiktok['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'] = df_tiktok['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'].apply(str_to_int)

df_tiktok['–ü—Ä–æ—Å–º–æ—Ç—Ä—ã'] = df_tiktok['–ü—Ä–æ—Å–º–æ—Ç—Ä—ã'].apply(str_to_int)

df_tiktok['–õ–∞–π–∫–∏'] = df_tiktok['–õ–∞–π–∫–∏'].apply(str_to_int)

df_tiktok['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'] = df_tiktok['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'].apply(str_to_int)

df_tiktok['–†–µ–ø–æ—Å—Ç—ã'] = df_tiktok['–†–µ–ø–æ—Å—Ç—ã'].apply(str_to_int)

–°–¥–µ–ª–∞–µ–º –∫–æ–ª–æ–Ω–∫—É —Å —Ä–∞–Ω–≥–æ–º –±–ª–æ–≥–µ—Ä–æ–≤ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤.

In [20]:
def tiktok_ranking(sub_count):
    '''
    –§—É–Ω–∫—Ü–∏—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Ä–∞–Ω–≥ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –ø–µ—Ä–µ–¥–∞–Ω–Ω–æ–≥–æ —á–∏—Å–ª–∞.
    –ë–æ–ª—å—à–µ 35 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–µ–≥–∞".
    –ë–æ–ª—å—à–µ 10 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 35 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∞–∫—Ä–æ".
    –ë–æ–ª—å—à–µ 3 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 10 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∏–∫—Ä–æ".
    –ú–µ–Ω—å—à–µ 3 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ù–∞–Ω–æ".
    '''
    if sub_count > 35000000:
        return '–ú–µ–≥–∞ (>35M)'
    elif (sub_count > 10000000) and (sub_count < 35000000):
        return '–ú–∞–∫—Ä–æ (>10M) & (<35M)'
    elif (sub_count > 3000000) and (sub_count < 10000000):
        return '–ú–∏–∫—Ä–æ (>3M) & (<10M)'
    else:
        return '–ù–∞–Ω–æ (<3M)'

In [21]:
df_tiktok['–†–∞–Ω–≥'] = df_tiktok['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'].apply(tiktok_ranking)

–£–¥–∞–ª–∏–º –¥—É–±–ª–∏–∫–∞—Ç—ã –∏ –ø—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.

In [22]:
df_tiktok = df_tiktok.drop_duplicates()
df_tiktok = df_tiktok.dropna()
df_tiktok

,–ù–∏–∫ TikTok,–ò–º—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–†–µ–ø–æ—Å—Ç—ã,–†–∞–Ω–≥
0,mrbeast,MrBeast,60300000.0,29200000.0,3500000.0,30800.0,7200.0,–ú–µ–≥–∞ (>35M)
1,karolg,Karol G,42400000.0,23700000.0,3400000.0,21700.0,25700.0,–ú–µ–≥–∞ (>35M)
2,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8900000.0,48900000.0,998400.0,16300.0,60900.0,–ú–∏–∫—Ä–æ (>3M) & (<10M)
3,centralcee,CentralCee,4400000.0,19800000.0,3600000.0,23300.0,24200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M)
4,adinross,adin,6100000.0,21100000.0,3300000.0,17500.0,25300.0,–ú–∏–∫—Ä–æ (>3M) & (<10M)
...,...,...,...,...,...,...,...,...
995,jiembasands,Jiemba Sands,4900000.0,3400000.0,247400.0,207.0,264.0,–ú–∏–∫—Ä–æ (>3M) & (<10M)
996,crissa_ace,Crissa Jackson,14900000.0,1600000.0,141700.0,1200.0,580.0,–ú–∞–∫—Ä–æ (>10M) & (<35M)
997,ichadude,Alyssa & Dude,468800.0,2300000.0,85500.0,997.0,1000.0,–ù–∞–Ω–æ (<3M)
998,kanebrown,Kane Brown,5200000.0,1700000.0,96700.0,1300.0,1200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M)
999,nnennab_,Nnenna B | NYC Creator & Actor,149100.0,606200.0,79500.0,2100.0,6100.0,–ù–∞–Ω–æ (<3M)

–ö–∞–∫–æ–º –æ–±—Ä–∞–∑–æ–º —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–∏–ª–∏—Å—å —Ä–∞–Ω–≥–∏ –±–ª–æ–≥–µ—Ä–æ–≤?

In [23]:
df_tiktok['–†–∞–Ω–≥'].value_counts()

–†–∞–Ω–≥
–ú–∏–∫—Ä–æ (>3M) & (<10M)     386
–ù–∞–Ω–æ (<3M)               383
–ú–∞–∫—Ä–æ (>10M) & (<35M)    198
–ú–µ–≥–∞ (>35M)               32
Name: count, dtype: int64

–°–¥–µ–ª–∞–µ–º –Ω–æ–≤—É—é –∫–æ–ª–æ–Ω–∫—É —Å –º–µ—Ç—Ä–∏–∫–æ–π "–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å", –∑–∞–ø–∏—à–µ–º —Ç—É–¥–∞ –æ—Ç–Ω–æ—à–µ–Ω–∏–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –ª–∞–π–∫–æ–≤ –∫ –∫–æ–ª–∏—á–µ—Å—Ç–≤—É –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤.

In [24]:
df_tiktok['–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å'] = round((df_tiktok['–õ–∞–π–∫–∏'] / df_tiktok['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏']) * 100)
df_tiktok

,–ù–∏–∫ TikTok,–ò–º—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–†–µ–ø–æ—Å—Ç—ã,–†–∞–Ω–≥,–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å
0,mrbeast,MrBeast,60300000.0,29200000.0,3500000.0,30800.0,7200.0,–ú–µ–≥–∞ (>35M),6.0
1,karolg,Karol G,42400000.0,23700000.0,3400000.0,21700.0,25700.0,–ú–µ–≥–∞ (>35M),8.0
2,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8900000.0,48900000.0,998400.0,16300.0,60900.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),11.0
3,centralcee,CentralCee,4400000.0,19800000.0,3600000.0,23300.0,24200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),82.0
4,adinross,adin,6100000.0,21100000.0,3300000.0,17500.0,25300.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),54.0
...,...,...,...,...,...,...,...,...,...
995,jiembasands,Jiemba Sands,4900000.0,3400000.0,247400.0,207.0,264.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),5.0
996,crissa_ace,Crissa Jackson,14900000.0,1600000.0,141700.0,1200.0,580.0,–ú–∞–∫—Ä–æ (>10M) & (<35M),1.0
997,ichadude,Alyssa & Dude,468800.0,2300000.0,85500.0,997.0,1000.0,–ù–∞–Ω–æ (<3M),18.0
998,kanebrown,Kane Brown,5200000.0,1700000.0,96700.0,1300.0,1200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),2.0
999,nnennab_,Nnenna B | NYC Creator & Actor,149100.0,606200.0,79500.0,2100.0,6100.0,–ù–∞–Ω–æ (<3M),53.0

–°–¥–µ–ª–∞–µ–º —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –±–ª–æ–≥–µ—Ä–æ–≤ –ø–æ —É—Ä–æ–≤–Ω—é –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏.

In [25]:
def tiktok_attraction_level(attraction):
    '''
    –§—É–Ω–∫—Ü–∏—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç —É—Ä–æ–≤–µ–Ω—å –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –ø–µ—Ä–µ–¥–∞–Ω–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è.
    –ë–æ–ª—å—à–µ –∏–ª–∏ —Ä–∞–≤–Ω–æ 150 - "–í—ã—Å–æ–∫–∏–π".
    –ë–æ–ª—å—à–µ –∏–ª–∏ —Ä–∞–≤–Ω–æ 50 –∏ –º–µ–Ω—å—à–µ 150 - "–°—Ä–µ–¥–Ω–∏–π".
    –ú–µ–Ω—å—à–µ 50 - "–ù–∏–∑–∫–∏–π".
    '''
    if attraction >= 150:
        return '–í—ã—Å–æ–∫–∏–π'
    elif (attraction >= 50) and (attraction < 150):
        return '–°—Ä–µ–¥–Ω–∏–π'
    else:
        return '–ù–∏–∑–∫–∏–π'

In [26]:
df_tiktok['–£—Ä–æ–≤–µ–Ω—å –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏'] = df_tiktok['–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å'].apply(tiktok_attraction_level)

–°–¥–µ–ª–∞–µ–º –Ω–æ–≤—É—é –∫–æ–ª–æ–Ω–∫—É —Å –º–µ—Ç—Ä–∏–∫–æ–π "–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å", –∑–∞–ø–∏—à–µ–º —Ç—É–¥–∞ —Å—É–º–º—É –ª–∞–π–∫–æ–≤, –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –∏ —Ä–µ–ø–æ—Å—Ç–æ–≤.

In [27]:
df_tiktok['–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å'] = df_tiktok['–õ–∞–π–∫–∏'] + df_tiktok['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'] + df_tiktok['–†–µ–ø–æ—Å—Ç—ã']
df_tiktok

,–ù–∏–∫ TikTok,–ò–º—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–†–µ–ø–æ—Å—Ç—ã,–†–∞–Ω–≥,–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å,–£—Ä–æ–≤–µ–Ω—å –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å
0,mrbeast,MrBeast,60300000.0,29200000.0,3500000.0,30800.0,7200.0,–ú–µ–≥–∞ (>35M),6.0,–ù–∏–∑–∫–∏–π,3538000.0
1,karolg,Karol G,42400000.0,23700000.0,3400000.0,21700.0,25700.0,–ú–µ–≥–∞ (>35M),8.0,–ù–∏–∑–∫–∏–π,3447400.0
2,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8900000.0,48900000.0,998400.0,16300.0,60900.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),11.0,–ù–∏–∑–∫–∏–π,1075600.0
3,centralcee,CentralCee,4400000.0,19800000.0,3600000.0,23300.0,24200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),82.0,–°—Ä–µ–¥–Ω–∏–π,3647500.0
4,adinross,adin,6100000.0,21100000.0,3300000.0,17500.0,25300.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),54.0,–°—Ä–µ–¥–Ω–∏–π,3342800.0
...,...,...,...,...,...,...,...,...,...,...,...
995,jiembasands,Jiemba Sands,4900000.0,3400000.0,247400.0,207.0,264.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),5.0,–ù–∏–∑–∫–∏–π,247871.0
996,crissa_ace,Crissa Jackson,14900000.0,1600000.0,141700.0,1200.0,580.0,–ú–∞–∫—Ä–æ (>10M) & (<35M),1.0,–ù–∏–∑–∫–∏–π,143480.0
997,ichadude,Alyssa & Dude,468800.0,2300000.0,85500.0,997.0,1000.0,–ù–∞–Ω–æ (<3M),18.0,–ù–∏–∑–∫–∏–π,87497.0
998,kanebrown,Kane Brown,5200000.0,1700000.0,96700.0,1300.0,1200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),2.0,–ù–∏–∑–∫–∏–π,99200.0
999,nnennab_,Nnenna B | NYC Creator & Actor,149100.0,606200.0,79500.0,2100.0,6100.0,–ù–∞–Ω–æ (<3M),53.0,–°—Ä–µ–¥–Ω–∏–π,87700.0

–°–¥–µ–ª–∞–µ–º —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –±–ª–æ–≥–µ—Ä–æ–≤ –ø–æ —É—Ä–æ–≤–Ω—é –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏.

In [28]:
def tiktok_involvement_level(involvement):
    '''
    –§—É–Ω–∫—Ü–∏—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç —É—Ä–æ–≤–µ–Ω—å –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –ø–µ—Ä–µ–¥–∞–Ω–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è.
    –ë–æ–ª—å—à–µ –∏–ª–∏ —Ä–∞–≤–Ω–æ 1.5 –º–ª–Ω. - "–í—ã—Å–æ–∫–∏–π".
    –ë–æ–ª—å—à–µ –∏–ª–∏ —Ä–∞–≤–Ω–æ 200 —Ç—ã—Å. –∏ –º–µ–Ω—å—à–µ 1.5 –º–ª–Ω. - "–°—Ä–µ–¥–Ω–∏–π".
    –ú–µ–Ω—å—à–µ 200 —Ç—ã—Å. - "–ù–∏–∑–∫–∏–π".
    '''
    if involvement >= 1500000:
        return '–í—ã—Å–æ–∫–∏–π'
    elif (involvement >= 200000) and (involvement < 1500000):
        return '–°—Ä–µ–¥–Ω–∏–π'
    else:
        return '–ù–∏–∑–∫–∏–π'

In [29]:
df_tiktok['–£—Ä–æ–≤–µ–Ω—å –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏'] = df_tiktok['–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å'].apply(tiktok_involvement_level)

–£–¥–∞–ª–∏–º –∫–æ–ª–æ–Ω–∫–∏ —Å —á–∏—Å–ª–æ–≤—ã–º–∏ –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∏ –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏, –æ—Å—Ç–∞–≤–∏–º —Ç–æ–ª—å–∫–æ —É—Ä–æ–≤–Ω–∏.

In [30]:
df_tiktok = df_tiktok.drop(columns=['–ü—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å', '–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å'])
df_tiktok

,–ù–∏–∫ TikTok,–ò–º—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–†–µ–ø–æ—Å—Ç—ã,–†–∞–Ω–≥,–£—Ä–æ–≤–µ–Ω—å –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ—Å—Ç–∏,–£—Ä–æ–≤–µ–Ω—å –≤–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç–∏
0,mrbeast,MrBeast,60300000.0,29200000.0,3500000.0,30800.0,7200.0,–ú–µ–≥–∞ (>35M),–ù–∏–∑–∫–∏–π,–í—ã—Å–æ–∫–∏–π
1,karolg,Karol G,42400000.0,23700000.0,3400000.0,21700.0,25700.0,–ú–µ–≥–∞ (>35M),–ù–∏–∑–∫–∏–π,–í—ã—Å–æ–∫–∏–π
2,yzn47,Ÿäÿ≤ŸÜ ÿßŸÑÿ£ÿ≥ŸÖÿ±,8900000.0,48900000.0,998400.0,16300.0,60900.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),–ù–∏–∑–∫–∏–π,–°—Ä–µ–¥–Ω–∏–π
3,centralcee,CentralCee,4400000.0,19800000.0,3600000.0,23300.0,24200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),–°—Ä–µ–¥–Ω–∏–π,–í—ã—Å–æ–∫–∏–π
4,adinross,adin,6100000.0,21100000.0,3300000.0,17500.0,25300.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),–°—Ä–µ–¥–Ω–∏–π,–í—ã—Å–æ–∫–∏–π
...,...,...,...,...,...,...,...,...,...,...
995,jiembasands,Jiemba Sands,4900000.0,3400000.0,247400.0,207.0,264.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),–ù–∏–∑–∫–∏–π,–°—Ä–µ–¥–Ω–∏–π
996,crissa_ace,Crissa Jackson,14900000.0,1600000.0,141700.0,1200.0,580.0,–ú–∞–∫—Ä–æ (>10M) & (<35M),–ù–∏–∑–∫–∏–π,–ù–∏–∑–∫–∏–π
997,ichadude,Alyssa & Dude,468800.0,2300000.0,85500.0,997.0,1000.0,–ù–∞–Ω–æ (<3M),–ù–∏–∑–∫–∏–π,–ù–∏–∑–∫–∏–π
998,kanebrown,Kane Brown,5200000.0,1700000.0,96700.0,1300.0,1200.0,–ú–∏–∫—Ä–æ (>3M) & (<10M),–ù–∏–∑–∫–∏–π,–ù–∏–∑–∫–∏–π
999,nnennab_,Nnenna B | NYC Creator & Actor,149100.0,606200.0,79500.0,2100.0,6100.0,–ù–∞–Ω–æ (<3M),–°—Ä–µ–¥–Ω–∏–π,–ù–∏–∑–∫–∏–π

In [31]:
# –°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ –¥–∞—Ç–∞—Å–µ—Ç–∞
# df_tiktok.to_excel('data/df_tiktok.xlsx', index=False)

# 3. YouTube

In [32]:
# –ó–∞–≥—Ä—É–∑–∫–∞ –¥–∞–Ω–Ω—ã—Ö
df_youtube = pd.read_csv('data/youtube/social media influencers-YOUTUBE - --DEC 2022.csv')
print(df_youtube.shape)
df_youtube.head()

(1003, 10)

,s.no,Youtube channel,youtuber name,Category,Followers,Country,\nViews (Avg.),Likes (Avg.),Comments (Avg.),Category-2
0,1,tseries,T-Series,Music & Dance,229.5M,India,103.8K,2.8K,158,NaN
1,2,setindia,SET India,NaN,147.2M,India,0,0,0,NaN
2,3,checkgate,Cocomelon - Nursery Rhymes,Education,146.6M,NaN,9.5M,48.3K,0,NaN
3,4,MrBeast,MrBeast,Video games,117M,United States,68.5M,2.9M,99.9K,Humor
4,5,PewDiePie,PewDiePie,Animation,111.6M,United States,1.4M,110.7K,7.8K,NaN

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –Ω—É–∂–Ω—ã–µ –∫–æ–ª–æ–Ω–∫–∏, –æ—Å—Ç–∞–ª—å–Ω—ã–µ —É–¥–∞–ª–∏–º.

In [33]:
df_youtube = df_youtube.drop(columns=['s.no', 'Category-2'])

df_youtube = df_youtube.rename(columns={'youtuber name': '–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞',
                                        'Youtube channel': '–ù–∏–∫ YouTube',
                                        'Country': '–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è',
                                        'Followers': '–ü–æ–¥–ø–∏—Å—á–∏–∫–∏',
                                        '\nViews (Avg.)': '–ü—Ä–æ—Å–º–æ—Ç—Ä—ã',
                                        'Likes (Avg.)': '–õ–∞–π–∫–∏',
                                        'Comments (Avg.)': '–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏',
                                        'Category': '–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞'})

df_youtube = df_youtube[['–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞', '–ù–∏–∫ YouTube', '–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è', '–ü–æ–¥–ø–∏—Å—á–∏–∫–∏', '–ü—Ä–æ—Å–º–æ—Ç—Ä—ã', '–õ–∞–π–∫–∏', '–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏', '–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞']]

df_youtube

,–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞,–ù–∏–∫ YouTube,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞
0,T-Series,tseries,India,229.5M,103.8K,2.8K,158,Music & Dance
1,SET India,setindia,India,147.2M,0,0,0,NaN
2,Cocomelon - Nursery Rhymes,checkgate,NaN,146.6M,9.5M,48.3K,0,Education
3,MrBeast,MrBeast,United States,117M,68.5M,2.9M,99.9K,Video games
4,PewDiePie,PewDiePie,United States,111.6M,1.4M,110.7K,7.8K,Animation
...,...,...,...,...,...,...,...,...
998,Classic Mr Bean,ClassicMrBean,India,10.1M,48.3K,624,23,NaN
999,Anupam Movie Songs,Anupam Movie Songs,Bangladesh,10.1M,41.2K,315,18,Music & Dance
1000,Anand Audio,AnandAudio,India,10.3M,175.5K,2.2K,109,NaN
1001,Wylsacom,Wylsacom,Russia,10.3M,291.7K,13K,950,Science & Technology
1002,Eagle Home Entertainments,Eagle Home Entertainments,India,10.2M,724,3,0,NaN

–ü–æ—Å–º–æ—Ç—Ä–∏–º, –µ—Å—Ç—å –ª–∏ –≤ –¥–∞–Ω–Ω—ã—Ö –ø—Ä–æ–ø—É—Å–∫–∏.

In [34]:
df_youtube.isnull().sum()

–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞         0
–ù–∏–∫ YouTube             0
–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è    177
–ü–æ–¥–ø–∏—Å—á–∏–∫–∏              0
–ü—Ä–æ—Å–º–æ—Ç—Ä—ã               0
–õ–∞–π–∫–∏                   0
–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏             0
–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞    297
dtype: int64

In [35]:
df_youtube.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   –ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞     1003 non-null   object
 1   –ù–∏–∫ YouTube         1003 non-null   object
 2   –û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è  826 non-null    object
 3   –ü–æ–¥–ø–∏—Å—á–∏–∫–∏          1003 non-null   object
 4   –ü—Ä–æ—Å–º–æ—Ç—Ä—ã           1003 non-null   object
 5   –õ–∞–π–∫–∏               1003 non-null   object
 6   –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏         1003 non-null   object
 7   –ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞  706 non-null    object
dtypes: object(8)
memory usage: 62.8+ KB

–ß–∏—Å–ª–æ–≤—ã–µ –¥–∞–Ω–Ω—ã–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω—ã –≤ –≤–∏–¥–µ —Å—Ç—Ä–æ–∫, –ø–æ—ç—Ç–æ–º—É –ø—Ä–æ–≤–µ–¥–µ–º –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –∫ —á–∏—Å–ª–æ–≤–æ–º—É —Ç–∏–ø—É –¥–∞–Ω–Ω—ã—Ö.

In [36]:
df_youtube['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'] = df_youtube['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'] .apply(str_to_int)

df_youtube['–ü—Ä–æ—Å–º–æ—Ç—Ä—ã'] = df_youtube['–ü—Ä–æ—Å–º–æ—Ç—Ä—ã'].apply(str_to_int)

df_youtube['–õ–∞–π–∫–∏'] = df_youtube['–õ–∞–π–∫–∏'].apply(str_to_int)

df_youtube['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'] = df_youtube['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'].apply(str_to_int)

–°–¥–µ–ª–∞–µ–º –∫–æ–ª–æ–Ω–∫—É —Å —Ä–∞–Ω–≥–æ–º –±–ª–æ–≥–µ—Ä–æ–≤ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤.

In [37]:
def youtube_ranking(sub_count):
    '''
    –§—É–Ω–∫—Ü–∏—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç —Ä–∞–Ω–≥ –≤ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ –æ—Ç –ø–µ—Ä–µ–¥–∞–Ω–Ω–æ–≥–æ —á–∏—Å–ª–∞.
    –ë–æ–ª—å—à–µ 50 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–µ–≥–∞".
    –ë–æ–ª—å—à–µ 30 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 50 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∞–∫—Ä–æ".
    –ë–æ–ª—å—à–µ 15 –º–∏–ª–ª–∏–æ–Ω–æ–≤ –∏ –º–µ–Ω—å—à–µ 30 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ú–∏–∫—Ä–æ".
    –ú–µ–Ω—å—à–µ 15 –º–∏–ª–ª–∏–æ–Ω–æ–≤ - "–ù–∞–Ω–æ".
    '''
    if sub_count > 50000000:
        return '–ú–µ–≥–∞ (>50M)'
    elif (sub_count > 30000000) and (sub_count < 50000000):
        return '–ú–∞–∫—Ä–æ (>30M) & (<50M)'
    elif (sub_count > 15000000) and (sub_count < 30000000):
        return '–ú–∏–∫—Ä–æ (>15M) & (<30M)'
    else:
        return '–ù–∞–Ω–æ (<15M)'

In [38]:
df_youtube['–†–∞–Ω–≥'] = df_youtube['–ü–æ–¥–ø–∏—Å—á–∏–∫–∏'].apply(youtube_ranking)

–£–¥–∞–ª–∏–º –¥—É–±–ª–∏–∫–∞—Ç—ã –∏ –ø—É—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è.

In [39]:
df_youtube = df_youtube.drop_duplicates()
df_youtube = df_youtube.dropna()
df_youtube

,–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞,–ù–∏–∫ YouTube,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,T-Series,tseries,India,229500000.0,103800.0,2800.0,158.0,Music & Dance,–ú–µ–≥–∞ (>50M)
3,MrBeast,MrBeast,United States,117000000.0,68500000.0,2900000.0,99900.0,Video games,–ú–µ–≥–∞ (>50M)
4,PewDiePie,PewDiePie,United States,111600000.0,1400000.0,110700.0,7800.0,Animation,–ú–µ–≥–∞ (>50M)
7,WWE,WWEFanNation,United States,91800000.0,144900.0,5100.0,207.0,Video games,–ú–µ–≥–∞ (>50M)
9,Zee Music Company,zeemusiccompany,India,89700000.0,89600.0,2400.0,91.0,Music & Dance,–ú–µ–≥–∞ (>50M)
...,...,...,...,...,...,...,...,...,...
984,Roshan Zindagi,Roshan Zindagi,India,10200000.0,21200.0,652.0,15.0,Education,–ù–∞–Ω–æ (<15M)
989,Sab Kuchh Sekho Jano,Sabkuchhsikhojano,India,10100000.0,11800.0,1200.0,72.0,News & Politics,–ù–∞–Ω–æ (<15M)
991,Fox News,FoxNewsChannel,United States,10100000.0,98400.0,4000.0,884.0,News & Politics,–ù–∞–Ω–æ (<15M)
992,Santa Fe Klan Official,Santa Fe Klan Official,Mexico,10100000.0,0.0,0.0,0.0,Music & Dance,–ù–∞–Ω–æ (<15M)
999,Anupam Movie Songs,Anupam Movie Songs,Bangladesh,10100000.0,41200.0,315.0,18.0,Music & Dance,–ù–∞–Ω–æ (<15M)

–ö–∞–∫–æ–º –æ–±—Ä–∞–∑–æ–º —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–∏–ª–∏—Å—å —Ä–∞–Ω–≥–∏ –±–ª–æ–≥–µ—Ä–æ–≤?

In [40]:
df_youtube['–†–∞–Ω–≥'].value_counts()

–†–∞–Ω–≥
–ù–∞–Ω–æ (<15M)              321
–ú–∏–∫—Ä–æ (>15M) & (<30M)    199
–ú–∞–∫—Ä–æ (>30M) & (<50M)     38
–ú–µ–≥–∞ (>50M)               20
Name: count, dtype: int64

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –∑–Ω–∞—á–µ–Ω–∏—è –∫–æ–ª–æ–Ω–∫–∏ —Å–æ —Å—Ç—Ä–∞–Ω–∞–º–∏ –∞—É–¥–∏—Ç–æ—Ä–∏–∏.

In [41]:
df_youtube = df_youtube.replace({'–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è': {'India': '–ò–Ω–¥–∏—è',
                                                        'United States': '–°–®–ê',
                                                        'Brazil': '–ë—Ä–∞–∑–∏–ª–∏—è',
                                                        'Mexico': '–ú–µ–∫—Å–∏–∫–∞',
                                                        'Russia': '–†–æ—Å—Å–∏—è',
                                                        'Colombia': '–ö–æ–ª—É–º–±–∏—è',
                                                        'France': '–§—Ä–∞–Ω—Ü–∏—è',
                                                        'Indonesia': '–ò–Ω–¥–æ–Ω–µ–∑–∏—è',
                                                        'Iraq': '–ò—Ä–∞–∫',
                                                        'Philippines': '–§–∏–ª–∏–ø–ø–∏–Ω—ã',
                                                        'Turkey': '–¢—É—Ä—Ü–∏—è',
                                                        'Thailand': '–¢–∞–∏–ª–∞–Ω–¥',
                                                        'Argentina': '–ê—Ä–≥–µ–Ω—Ç–∏–Ω–∞',
                                                        'Saudi Arabia': '–°–∞—É–¥–æ–≤—Å–∫–∞—è –ê—Ä–∞–≤–∏—è',
                                                        'United Kingdom': '–í–µ–ª–∏–∫–æ–±—Ä–∏—Ç–∞–Ω–∏—è',
                                                        'Spain': '–ò—Å–ø–∞–Ω–∏—è',
                                                        'Bangladesh': '–ë–∞–Ω–≥–ª–∞–¥–µ—à',
                                                        'Pakistan': '–ü–∞–∫–∏—Å—Ç–∞–Ω',
                                                        'Jordan': '–ò–æ—Ä–¥–∞–Ω–∏—è',
                                                        'Peru': '–ü–µ—Ä—É',
                                                        'Algeria': '–ê–ª–∂–∏—Ä',
                                                        'Japan': '–Ø–ø–æ–Ω–∏—è',
                                                        'Morocco': '–ú–∞—Ä–æ–∫–∫–æ',
                                                        'Somalia': '–°–æ–º–∞–ª–∏'}})

df_youtube

,–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞,–ù–∏–∫ YouTube,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,T-Series,tseries,–ò–Ω–¥–∏—è,229500000.0,103800.0,2800.0,158.0,Music & Dance,–ú–µ–≥–∞ (>50M)
3,MrBeast,MrBeast,–°–®–ê,117000000.0,68500000.0,2900000.0,99900.0,Video games,–ú–µ–≥–∞ (>50M)
4,PewDiePie,PewDiePie,–°–®–ê,111600000.0,1400000.0,110700.0,7800.0,Animation,–ú–µ–≥–∞ (>50M)
7,WWE,WWEFanNation,–°–®–ê,91800000.0,144900.0,5100.0,207.0,Video games,–ú–µ–≥–∞ (>50M)
9,Zee Music Company,zeemusiccompany,–ò–Ω–¥–∏—è,89700000.0,89600.0,2400.0,91.0,Music & Dance,–ú–µ–≥–∞ (>50M)
...,...,...,...,...,...,...,...,...,...
984,Roshan Zindagi,Roshan Zindagi,–ò–Ω–¥–∏—è,10200000.0,21200.0,652.0,15.0,Education,–ù–∞–Ω–æ (<15M)
989,Sab Kuchh Sekho Jano,Sabkuchhsikhojano,–ò–Ω–¥–∏—è,10100000.0,11800.0,1200.0,72.0,News & Politics,–ù–∞–Ω–æ (<15M)
991,Fox News,FoxNewsChannel,–°–®–ê,10100000.0,98400.0,4000.0,884.0,News & Politics,–ù–∞–Ω–æ (<15M)
992,Santa Fe Klan Official,Santa Fe Klan Official,–ú–µ–∫—Å–∏–∫–∞,10100000.0,0.0,0.0,0.0,Music & Dance,–ù–∞–Ω–æ (<15M)
999,Anupam Movie Songs,Anupam Movie Songs,–ë–∞–Ω–≥–ª–∞–¥–µ—à,10100000.0,41200.0,315.0,18.0,Music & Dance,–ù–∞–Ω–æ (<15M)

–ü–µ—Ä–µ–∏–º–µ–Ω—É–µ–º –∑–Ω–∞—á–µ–Ω–∏—è –∫–æ–ª–æ–Ω–∫–∏ —Å –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º–∏ –∫–æ–Ω—Ç–µ–Ω—Ç–∞.

In [42]:
df_youtube = df_youtube.replace({'–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞': {'Music & Dance': '–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã',
                                                        'Video games': '–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã',
                                                        'Animation': '–ê–Ω–∏–º–∞—Ü–∏—è',
                                                        'Movies': '–ö–∏–Ω–æ',
                                                        'News & Politics': '–ù–æ–≤–æ—Å—Ç–∏ –∏ –ü–æ–ª–∏—Ç–∏–∫–∞',
                                                        'Daily vlogs': '–ï–∂–µ–¥–Ω–µ–≤–Ω—ã–π –≤–ª–æ–≥',
                                                        'Humor': '–Æ–º–æ—Ä',
                                                        'Fitness': '–§–∏—Ç–Ω–µ—Å',
                                                        'Food & Drinks': '–ï–¥–∞ –∏ –ù–∞–ø–∏—Ç–∫–∏',
                                                        'Beauty': '–ö—Ä–∞—Å–æ—Ç–∞',
                                                        'DIY & Life Hacks': 'DIY –∏ –õ–∞–π—Ñ—Ö–∞–∫–∏',
                                                        'Science & Technology': '–ù–∞—É–∫–∞ –∏ –¢–µ—Ö–Ω–æ–ª–æ–≥–∏–∏',
                                                        'Sports': '–°–ø–æ—Ä—Ç',
                                                        'Education': '–û–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ',
                                                        'Toys': '–ò–≥—Ä—É—à–∫–∏',
                                                        'Health & Self Help': '–ó–¥–æ—Ä–æ–≤—å–µ',
                                                        'Animals & Pets': '–ñ–∏–≤–æ—Ç–Ω—ã–µ',
                                                        'ASMR': 'ASMR',
                                                        'Design/art': '–î–∏–∑–∞–π–Ω/–†–∏—Å–æ–≤–∞–Ω–∏–µ',
                                                        'Fashion': '–ú–æ–¥–∞',
                                                        'Travel': '–ü—É—Ç–µ—à–µ—Å—Ç–≤–∏—è'}})

df_youtube

,–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞,–ù–∏–∫ YouTube,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥
0,T-Series,tseries,–ò–Ω–¥–∏—è,229500000.0,103800.0,2800.0,158.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ú–µ–≥–∞ (>50M)
3,MrBeast,MrBeast,–°–®–ê,117000000.0,68500000.0,2900000.0,99900.0,–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã,–ú–µ–≥–∞ (>50M)
4,PewDiePie,PewDiePie,–°–®–ê,111600000.0,1400000.0,110700.0,7800.0,–ê–Ω–∏–º–∞—Ü–∏—è,–ú–µ–≥–∞ (>50M)
7,WWE,WWEFanNation,–°–®–ê,91800000.0,144900.0,5100.0,207.0,–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã,–ú–µ–≥–∞ (>50M)
9,Zee Music Company,zeemusiccompany,–ò–Ω–¥–∏—è,89700000.0,89600.0,2400.0,91.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ú–µ–≥–∞ (>50M)
...,...,...,...,...,...,...,...,...,...
984,Roshan Zindagi,Roshan Zindagi,–ò–Ω–¥–∏—è,10200000.0,21200.0,652.0,15.0,–û–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ,–ù–∞–Ω–æ (<15M)
989,Sab Kuchh Sekho Jano,Sabkuchhsikhojano,–ò–Ω–¥–∏—è,10100000.0,11800.0,1200.0,72.0,–ù–æ–≤–æ—Å—Ç–∏ –∏ –ü–æ–ª–∏—Ç–∏–∫–∞,–ù–∞–Ω–æ (<15M)
991,Fox News,FoxNewsChannel,–°–®–ê,10100000.0,98400.0,4000.0,884.0,–ù–æ–≤–æ—Å—Ç–∏ –∏ –ü–æ–ª–∏—Ç–∏–∫–∞,–ù–∞–Ω–æ (<15M)
992,Santa Fe Klan Official,Santa Fe Klan Official,–ú–µ–∫—Å–∏–∫–∞,10100000.0,0.0,0.0,0.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ù–∞–Ω–æ (<15M)
999,Anupam Movie Songs,Anupam Movie Songs,–ë–∞–Ω–≥–ª–∞–¥–µ—à,10100000.0,41200.0,315.0,18.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ù–∞–Ω–æ (<15M)

–°–¥–µ–ª–∞–µ–º –Ω–æ–≤—É—é –∫–æ–ª–æ–Ω–∫—É —Å –º–µ—Ç—Ä–∏–∫–æ–π "–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤", –∑–∞–ø–∏—à–µ–º —Ç—É–¥–∞ —Å—É–º–º—É –ø—Ä–æ—Å–º–æ—Ç—Ä–æ–≤, –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–µ–≤ –∏ –ª–∞–π–∫–æ–≤.

In [43]:
df_youtube['–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤'] = df_youtube['–ü—Ä–æ—Å–º–æ—Ç—Ä—ã'] + df_youtube['–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏'] + df_youtube['–õ–∞–π–∫–∏']
df_youtube

,–ù–∞–∑–≤–∞–Ω–∏–µ –∫–∞–Ω–∞–ª–∞,–ù–∏–∫ YouTube,–û—Å–Ω–æ–≤–Ω–∞—è –∞—É–¥–∏—Ç–æ—Ä–∏—è,–ü–æ–¥–ø–∏—Å—á–∏–∫–∏,–ü—Ä–æ—Å–º–æ—Ç—Ä—ã,–õ–∞–π–∫–∏,–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏,–ö–∞—Ç–µ–≥–æ—Ä–∏—è –∫–æ–Ω—Ç–µ–Ω—Ç–∞,–†–∞–Ω–≥,–í–æ–≤–ª–µ—á–µ–Ω–Ω–æ—Å—Ç—å –ø–æ–¥–ø–∏—Å—á–∏–∫–æ–≤
0,T-Series,tseries,–ò–Ω–¥–∏—è,229500000.0,103800.0,2800.0,158.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ú–µ–≥–∞ (>50M),106758.0
3,MrBeast,MrBeast,–°–®–ê,117000000.0,68500000.0,2900000.0,99900.0,–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã,–ú–µ–≥–∞ (>50M),71499900.0
4,PewDiePie,PewDiePie,–°–®–ê,111600000.0,1400000.0,110700.0,7800.0,–ê–Ω–∏–º–∞—Ü–∏—è,–ú–µ–≥–∞ (>50M),1518500.0
7,WWE,WWEFanNation,–°–®–ê,91800000.0,144900.0,5100.0,207.0,–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ –∏–≥—Ä—ã,–ú–µ–≥–∞ (>50M),150207.0
9,Zee Music Company,zeemusiccompany,–ò–Ω–¥–∏—è,89700000.0,89600.0,2400.0,91.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ú–µ–≥–∞ (>50M),92091.0
...,...,...,...,...,...,...,...,...,...,...
984,Roshan Zindagi,Roshan Zindagi,–ò–Ω–¥–∏—è,10200000.0,21200.0,652.0,15.0,–û–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ,–ù–∞–Ω–æ (<15M),21867.0
989,Sab Kuchh Sekho Jano,Sabkuchhsikhojano,–ò–Ω–¥–∏—è,10100000.0,11800.0,1200.0,72.0,–ù–æ–≤–æ—Å—Ç–∏ –∏ –ü–æ–ª–∏—Ç–∏–∫–∞,–ù–∞–Ω–æ (<15M),13072.0
991,Fox News,FoxNewsChannel,–°–®–ê,10100000.0,98400.0,4000.0,884.0,–ù–æ–≤–æ—Å—Ç–∏ –∏ –ü–æ–ª–∏—Ç–∏–∫–∞,–ù–∞–Ω–æ (<15M),103284.0
992,Santa Fe Klan Official,Santa Fe Klan Official,–ú–µ–∫—Å–∏–∫–∞,10100000.0,0.0,0.0,0.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ù–∞–Ω–æ (<15M),0.0
999,Anupam Movie Songs,Anupam Movie Songs,–ë–∞–Ω–≥–ª–∞–¥–µ—à,10100000.0,41200.0,315.0,18.0,–ú—É–∑—ã–∫–∞ –∏ –¢–∞–Ω—Ü—ã,–ù–∞–Ω–æ (<15M),41533.0

In [44]:
#df_youtube.to_excel('data/df_youtube.xlsx', index=False)